# Generated by Django 4.2 on 2024-09-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=32, verbose_name='Имя записи')),
                ('post_text', models.TextField(max_length=256, verbose_name='Текст поста')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_status', models.CharField(choices=[('not_published', 'Не опубликовано'), ('published', 'Опубликовано')], default='not_published', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
