# Generated by Django 4.2 on 2024-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('not_published', 'Не опубликовано'), ('published', 'Опубликовано')], default='not_published', max_length=15, verbose_name='Статус поста'),
        ),
    ]
